### ISSUE TITLE
Not compatible w/ releases greater than 0.36.12

### ISSUE THREAD

**Issue by 0x00A** [Level/electron-demo#31]
Fails to build with the following output

```
  LIBTOOL-STATIC Release/snappy.a
  CXX(target) Release/obj.target/leveldownhyper/src/batch.o
In file included from ../src/batch.cc:3:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/leveldownhyper/src/batch.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--target=0.37.3" "--arch=x64" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd /Users/u/p/node_modules/leveldown-hyper
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

**Comment by nolanlawson** [comment]
I tested 0.37.6 on OS X ElCap with Node 5.9 and it worked just fine. (I also merged the relevant PR from GK: https://github.com/Level/electron-demo/pull/33.) Maybe this is something that was fixed between 0.36.12 and 0.37.6? If not, please reopen.
