### ISSUE TITLE
webpack+leveluo not working

### ISSUE THREAD

**Issue by zhangmingze** [Level/electron-demo#56]
```shell
WARNING in ./~/.1.2.1@bindings/bindings.js
            Critical dependencies:
            76:22-40 the request of a dependency is an expression
            76:43-53 the request of a dependency is an expression
             @ ./~/.1.2.1@bindings/bindings.js 76:22-40 76:43-53

            WARNING in ./~/.1.2.1@bindings/README.md
            Module parse failed: C:\Users\mz\Desktop\vue-electron\node_modules\.1.2.1@bindings\README.md Unexpected token (2:3)
            You may need an appropriate loader to handle this file type.
            SyntaxError: Unexpected token (2:3)
                at Parser.pp$4.raise (C:\Users\mz\Desktop\vue-electron\node_modules\.3.3.0@acorn\dist\acorn.js:2221:15)
                at Parser.pp.unexpected (C:\Users\mz\Desktop\vue-electron\node_modules\.3.3.0@acorn\dist\acorn.js:603:10)
                at Parser.pp$3.parseExprAtom (C:\Users\mz\Desktop\vue-electron\node_modules\.3.3.0@acorn\dist\acorn.js:1822:12)
                at Parser.pp$3.parseExprSubscripts (C:\Users\mz\Desktop\vue-electron\node_modules\.3.3.0@acorn\dist\acorn.js:1715:21)
                at Parser.pp$3.parseMaybeUnary (C:\Users\mz\Desktop\vue-electron\node_modules\.3.3.0@acorn\dist\acorn.js:1692:19)
                at Parser.pp$3.parseExprOp (C:\Users\mz\Desktop\vue-electron\node_modules\.3.3.0@acorn\dist\acorn.js:1656:43)
                at Parser.pp$3.parseExprOp (C:\Users\mz\Desktop\vue-electron\node_modules\.3.3.0@acorn\dist\acorn.js:1658:21)
                at Parser.pp$3.parseExprOps (C:\Users\mz\Desktop\vue-electron\node_modules\.3.3.0@acorn\dist\acorn.js:1639:17)
                at Parser.pp$3.parseMaybeConditional (C:\Users\mz\Desktop\vue-electron\node_modules\.3.3.0@acorn\dist\acorn.js:1620:21)
                at Parser.pp$3.parseMaybeAssign (C:\Users\mz\Desktop\vue-electron\node_modules\.3.3.0@acorn\dist\acorn.js:1597:21)
                at Parser.pp$3.parseExpression (C:\Users\mz\Desktop\vue-electron\node_modules\.3.3.0@acorn\dist\acorn.js:1573:21)
                at Parser.pp$1.parseStatement (C:\Users\mz\Desktop\vue-electron\node_modules\.3.3.0@acorn\dist\acorn.js:727:47)
                at Parser.pp$1.parseTopLevel (C:\Users\mz\Desktop\vue-electron\node_modules\.3.3.0@acorn\dist\acorn.js:638:25)
                at Parser.parse (C:\Users\mz\Desktop\vue-electron\node_modules\.3.3.0@acorn\dist\acorn.js:516:17)
                at Object.parse (C:\Users\mz\Desktop\vue-electron\node_modules\.3.3.0@acorn\dist\acorn.js:3098:39)
                at Parser.parse (C:\Users\mz\Desktop\vue-electron\node_modules\.1.13.1@webpack\lib\Parser.js:902:15)
             @ ./~/.1.2.1@bindings ^\.\/.*$
```

the console log is path  is not a string

how can be work with webpack?

**Comment by juliangruber** [comment]
this is a webpack or vue issue, please report there
